# config.yaml

data:
  # data_path: "/project/biocomplexity/gza5dr/CAFO/NC_data/training_data"
  data_path: "/project/biocomplexity/gza5dr/CAFO/exp_v2/main_experiments/cafo_classification/datas/dataset/nc_training_data.json"
  # data_path: "/project/biocomplexity/gza5dr/CAFO/exp_v2/main_experiments/cafo_classification/datas/dataset/binary_dataset.json"
  # data_path: "/project/biocomplexity/gza5dr/CAFO/exp_v2/main_experiments/cafo_classification/datas/dataset/train_test_split_meter_ml.json"
  batch_size: 16
  mode: "json"
  

model:
  lr: 0.0001
  model_type: "vit_b_16"


trainer:
  max_epochs: 3
  accelerator: "auto"
  precision: 32


checkpoint:
  dirpath: "checkpoints"
  filename: "cafo_binaray_NC_vit"
  monitor: "val_acc"
  mode: "max"
  save_top_k: 1