data:
  # data_path: "/project/biocomplexity/gza5dr/CAFO/NC_data/training_data"
  data_path: "/project/biocomplexity/gza5dr/CAFO/NC_data/nc_training_data.json"
  batch_size: 16
  mode: "json"

model:
  lr: 1e-4
  model_type: "swin_b"

trainer:
  max_epochs: 3
  max_rounds: 10
  early_stop_patience: 2
  accelerator: "auto"
  precision: 32

checkpoint:
  dirpath: "/project/biocomplexity/gza5dr/CAFO/exp_v2/main_experiments/cafo_classification/checkpoints"
  filename: "cafo-best-{epoch:02d}-{val_acc:.2f}"
  monitor: "val_acc"
  mode: "max"
  save_top_k: 1


inference:
  categories:
    - Swine
    - Poultry
  input_dir: "/project/biocomplexity/gza5dr/CAFO/exp_v2/organized_cafo_dataset"
  verified_output: "/project/biocomplexity/gza5dr/CAFO/exp_v2/verified_cafo_3"

logging:
  csv_log: "logs/training_log.csv"
  save_predictions: true
  log_to_console: true
